name: Simple Static Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './'
        exclude: |
          .git/
          .github/
          node_modules/
          dist/
          *.md
          package*.json
          vite.config.ts
          tailwind.config.js
          postcss.config.js
          tsconfig*.json
          .gitignore
          
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4 